import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalPropProvider } from "./context/page";
import { ReactElement } from "react";

const inter = Inter({ subsets: ["latin"] });

type RootLayoutProps = {
  children: ReactElement;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalPropProvider>{children}</GlobalPropProvider>
      </body>
    </html>
  );
}
